name: deploy frontend to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup mdBook
      #   uses: peaceiris/actions-mdbook@v1
      #   with:
      #     mdbook-version: 'latest'

      # - run: mdbook build docs

      # - run: cd frontend && npm i && ls && npm run build
      # - run: cd frontend && npm i && ls && npm run build

      - name: Install and Build ðŸ”§ Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Install and Build ðŸ”§ Storybook
        run: |
          cd frontend
          npm run build-storybook
          cp -r storybook-static ./build/storybook
      
      - name: Deploy
        uses: iotaledger/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./frontend/build
          cname: dshop.einfachiota.de